# Generated by Django 2.1.5 on 2019-07-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new',
            field=models.CharField(default='True', max_length=7),
        ),
    ]
